{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    wget
    lua
    wl-clicker
    lua-language-server
    hollywood
    alacritty
    kitty
    ripgrep
    fd
    fzf
    fish
    zoxide
    unityhub
    claude-code
    atuin
    rust-analyzer
    ydotool
    intelephense
    wakeonlan
    tree
    stylua
    luarocks
    (prismlauncher.override {
      additionalLibs = with pkgs; [
        libXtst
        libX11
        libXi
        libXinerama
        libXrandr
        libxkbcommon
      ];
    })
    rink
    spotify
    spotifyd
    stow
    glib
    gobuster
    zulu8
    git
    lazygit
    wireshark
    openssl
    libreoffice
    nodejs
    pm2
    thunderbird
    google-chrome
    (pkgs.writeShellScriptBin "steam-run-xt" ''
      export LD_LIBRARY_PATH="${pkgs.libxt}/lib:$LD_LIBRARY_PATH"
      exec ${pkgs.steam-run}/bin/steam-run "$@"
    '')
    pulsemixer
    efibootmgr
    vscode
    bitwarden-desktop
    tree-sitter
    usbutils
    pkg-config
    pavucontrol
    file
    nwg-look
    emacsPackages.outlook
    libnotify
    discord
    wireguard-tools
    dirb
    iwd
    iwgtk
    adw-gtk3
    adwaita-icon-theme
    pamixer
    pyprland
    jq
    meson
    btop
    htop
    wpaperd
    hyprlandPlugins.csgo-vulkan-fix
    hyprpaper
    hyprlock
    hyprcursor
    hyprpanel
    lxappearance
    vulkan-tools
    curl
    rustc
    cmake
    unzip
    zip
    nautilus
    onedrive
    zsh
    grimblast
    php
    gparted
    figma-linux
    cliphist
    rpi-imager
    cura-appimage
    wl-clipboard
    bluez
    blueman
    cava
    heroic
    wine64
    winetricks
    mission-center
    playerctl
    wlogout
    swaynotificationcenter
    tokyonight-gtk-theme
    tela-icon-theme
    bibata-cursors
    kicad
    simulide
    unipicker
    geteduroam-cli
    rofi
    wofi
    cmatrix
    yazi
    pulseaudio
    toilet
    warp
    dunst
    fastfetch
    python314
    yt-dlp
    lsd
    friture
    hypridle
    brightnessctl
    zapzap
    arduino-ide
    libXtst
    libxkbfile
    jetbrains.rider
    jetbrains.phpstorm
    jamesdsp
    pay-respects
    nmap
    libgccjit
    gnumake42
    dotnet-sdk_8
    drawio
    icu
    sqlitebrowser
    python313Packages.pandas
    python313Packages.dbus-python

    php84Packages.composer 
    php84Extensions.pdo 
    php84Extensions.pdo_mysql
    laravel
    ddev
    mkcert

    libXtst
    libX11
    libXt
    libXinerama
    libxcb
    libxkbcommon
  ];
}
